name: kamusi
description: kiswahili kitukuzwe

version: 1.2.7+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_floatactionbuttons: ^0.1.0
  anisi_controls: ^0.0.7
  async: ^2.4.0
  auto_size_text: ^2.0.0+2
  change_app_package_name: ^0.1.2
  cupertino_icons: ^1.0.0
  freezed:
  freezed_annotation:
  firebase_analytics: ^5.0.11
  firebase_performance: ^0.3.1+8
  firebase_crashlytics: ^0.1.3+3
  flutter_custom_clippers: ^0.1.6
  font_awesome_flutter: ^8.4.0
  json_serializable: ^3.3.0
  flutter_html : ^1.0.2
  flutter_launcher_icons: ^0.7.5
  fluttertoast: ^7.0.2
  html_unescape: ^1.0.1+2
  http: ^0.12.0
  json_annotation: ^3.0.1
  loadmore: ^1.0.4
  responsive_widgets: ^2.0.1
  page_transition: ^1.1.6
  path_provider: ^1.6.11
  percent_indicator: ^2.1.3
  provider: ^4.3.2
  share: ^0.6.4+3
  shared_preferences: ^0.5.8
  shared_preferences_settings: ^1.2.0
  speech_recognition: ^0.3.0
  sqflite: ^1.3.1
  test: ^1.15.7
  url_launcher: ^5.4.2
  wakelock: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.1.2
  debug_mode: ^0.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon.png"

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/help/